### ISSUE TITLE
ApiRequest and MenuCall doesn't have cyrillic support

### ISSUE THREAD

**Issue by linkh** [phoxy/phoxy#100]

**Comment by Enelar** [comment]
Well. I know that issue, but i do not have solid solution on this.
Latest https://github.com/Enelar/phoxy/commit/cbadd8aaa69d4c4055033b88ddb5320543015a93 commit have temporary workaround on this - base64 encoding for everything.
This affects on url readablity, but keep in mind that it still unstable branch.

I have several optimisations planned in v1.5.0, please wait or help me to reach it : )

**Comment by Enelar** [comment]
@linkh Please check last version. Be aware, last merge completely change call reglament!
If you use `unstable` branch in production code, please consider to stick with staging v1.4
