### ISSUE TITLE
On async render strategy enjs ancors do not removing

### ISSUE THREAD

**Issue by MichaelRain** [phoxy/phoxy#137]
When using AsyncStrategy system keeps EJS_ANCORS in system, without removing them.

**Comment by Enelar** [comment]
AsyncStrategy should be refactored and become multithreaded as said https://github.com/phoxy/phoxy/issues/121

**Comment by Enelar** [comment]
Fixed https://github.com/phoxy/phoxy/commit/d33dc403917096a0c686b6e962ee34e8bbf8b7b8
